const countries = [
  'Andorra',
  'Vereinigte Arabische Emirate',
  'Afghanistan',
  'Antigua und Barbuda',
  'Anguilla',
  'Albanien',
  'Armenien',
  'Niederländische Antillen',
  'Angola',
  'Antarktis',
  'Argentinien',
  'Amerikanisch-Samoa',
  'Österreich (Austria)',
  'Australien',
  'Aruba',
  'Azerbaijan',
  'Bosnien-Herzegovina',
  'Barbados',
  'Bangladesh',
  'Belgien',
  'Burkina Faso',
  'Bulgarien',
  'Bahrain',
  'Burundi',
  'Benin',
  'Bermudas',
  'Brunei Darussalam',
  'Bolivien',
  'Brasilien',
  'Bahamas',
  'Bhutan',
  'Bouvet Island',
  'Botswana',
  'Weißrußland (Belarus)',
  'Belize',
  'Canada',
  'Cocos (Keeling) Islands',
  'Demokratische Republik Kongo',
  'Zentralafrikanische Republik',
  'Kongo',
  'Schweiz',
  "Elfenbeinküste (Cote D'Ivoire)",
  'Cook Islands',
  'Chile',
  'Kamerun',
  'China',
  'Kolumbien',
  'Costa Rica',
  'Tschechoslowakei (ehemalige)',
  'Kuba',
  'Kap Verde',
  'Christmas Island',
  'Zypern',
  'Tschechische Republik',
  'Deutschland',
  'Djibouti',
  'Dänemark',
  'Dominica',
  'Dominikanische Republik',
  'Algerien',
  'Ecuador',
  'Estland',
  'Ägypten',
  'Westsahara',
  'Eritrea',
  'Spanien',
  'Äthiopien',
  'Finnland',
  'Fiji',
  'Falkland-Inseln (Malvinas)',
  'Micronesien',
  'Faröer-Inseln',
  'Frankreich',
  'France, Metropolitan',
  'Gabon',
  'Grenada',
  'Georgien',
  'Französisch Guiana',
  'Ghana',
  'Gibraltar',
  'Grönland',
  'Gambia',
  'Guinea',
  'Guadeloupe',
  'Äquatorialguinea',
  'Griechenland',
  'Südgeorgien und Südliche Sandwich-Inseln',
  'Guatemala',
  'Guam',
  'Guinea-Bissau',
  'Guyana',
  'Kong Hong',
  'Heard und Mc Donald Islands',
  'Honduras',
  'Haiti',
  'Ungarn',
  'Indonesien',
  'Irland',
  'Israel',
  'Indien',
  'British Indian Ocean Territory',
  'Irak',
  'Iran (Islamische Republik)',
  'Island',
  'Italien',
  'Jamaica',
  'Jordanien',
  'Japan',
  'Kenya',
  'Kirgisien',
  'Königreich Kambodscha',
  'Kiribati',
  'Komoren',
  'Saint Kitts und Nevis',
  'Korea, Volksrepublik',
  'Korea',
  'Kuwait',
  'Kayman Islands',
  'Kasachstan',
  'Laos',
  'Libanon',
  'Saint Lucia',
  'Liechtenstein',
  'Sri Lanka',
  'Liberia',
  'Lesotho',
  'Littauen',
  'Luxemburg',
  'Lettland',
  'Libyen',
  'Marokko',
  'Monaco',
  'Moldavien',
  'Madagaskar',
  'Marshall-Inseln',
  'Mazedonien, ehem. Jugoslawische Republik',
  'Mali',
  'Myanmar',
  'Mongolei',
  'Macao',
  'Nördliche Marianneninseln',
  'Martinique',
  'Mauretanien',
  'Montserrat',
  'Malta',
  'Mauritius',
  'Malediven',
  'Malawi',
  'Mexico',
  'Malaysien',
  'Mozambique',
  'Namibia',
  'Neu Kaledonien',
  'Niger',
  'Norfolk Island',
  'Nigeria',
  'Nicaragua',
  'Niederlande',
  'Norwegen',
  'Nepal',
  'Nauru',
  'Niue',
  'Neuseeland',
  'Oman',
  'Panama',
  'Peru',
  'Französisch Polynesien',
  'Papua Neuguinea',
  'Philippinen',
  'Pakistan',
  'Polen',
  'St. Pierre und Miquelon',
  'Pitcairn',
  'Puerto Rico',
  'Portugal',
  'Palau',
  'Paraguay',
  'Katar',
  'Reunion',
  'Rumänien',
  'Russische Föderation',
  'Ruanda',
  'Saudi Arabien',
  'Salomonen',
  'Seychellen',
  'Sudan',
  'Schweden',
  'Singapur',
  'St. Helena',
  'Slovenien',
  'Svalbard und Jan Mayen Islands',
  'Slowakei',
  'Sierra Leone',
  'San Marino',
  'Senegal',
  'Somalia',
  'Surinam',
  'Sao Tome und Principe',
  'El Salvador',
  'Syrien, Arabische Republik',
  'Swaziland',
  'Turk und Caicos-Inseln',
  'Tschad',
  'Französisches Südl.Territorium',
  'Togo',
  'Thailand',
  'Tadschikistan',
  'Tokelau',
  'Turkmenistan',
  'Tunesien',
  'Tonga',
  'Ost-Timor',
  'Türkei',
  'Trinidad und Tobago',
  'Tuvalu',
  'Taiwan',
  'Tansania, United Republic of',
  'Ukraine',
  'Uganda',
  'Großbritannien',
  'Vereinigte Staaten',
  'Vereinigte Staaten, Minor Outlying Islands',
  'Uruguay',
  'Usbekistan',
  'Vatikanstaat',
  'Saint Vincent und Grenadines',
  'Venezuela',
  'Virgin Islands (Britisch)',
  'Virgin Islands (U.S.)',
  'Vietnam',
  'Vanuatu',
  'Wallis und Futuna Islands',
  'Samoa',
  'Jemen',
  'Mayotte',
  'Jugoslawien',
  'Südafrika',
  'Sambia',
  'Zimbabwe'
];

generateDiagram(
  'Politik',
  (() => {
    const singleWordFilter = word => ({
      name: word,
      f: el => el.text.toLowerCase().includes(word)
    });

    let view = generateDataView(true, onlyTrueAndFalse);
    [
      {
        name: 'all',
        f: el => true
      },
      singleWordFilter('deutsch'),
      singleWordFilter('politik'),
      singleWordFilter('migrant'),
      singleWordFilter('frau'),
      singleWordFilter('asyl'),
      singleWordFilter('flüchtlinge'),
      singleWordFilter('land'),
      singleWordFilter('rot'),
      singleWordFilter('grün'),
      singleWordFilter('presse'),
      {
        name: '*-*',
        f: el => new RegExp(/([A-Z][a-z]+\-)+[A-Z][a-z]+/g).test(el.text)
      },
      {
        name: '*-*',
        f: el => new RegExp(/([A-Z][a-z]+\-)+[A-Z][a-z]+/g).test(el.text)
      },
      {
        name: 'Recht',
        f: el => new RegExp(/recht/i).test(el.text)
      },
      {
        name: 'LänderListe',
        f: el => {
          for (let i = 0; i < countries.length; i++) {
            if(new RegExp(countries[i],'i').test(el.text)){
              return true;
            }
          }
          return false;
        }
      }
    ].forEach(filter => {
      addToView(filter, data, view);
    });
    return view;
  })()
);
